export const users = [
  {
    id: "user1",
    name: "Alex Johnson",
    username: "alexj",
    avatar: "/placeholder.svg",
    coverImage: "/placeholder.svg?height=300&width=800",
    bio: "Dog lover and outdoor enthusiast. My pets are my family!",
    location: "San Francisco, CA",
    posts: 42,
    followers: 1250,
    following: 365,
    pets: [
      {
        id: "pet1",
        name: "Max",
        species: "Dog",
        breed: "Golden Retriever",
        age: 3,
        gender: "Male",
        image: "/placeholder.svg?height=200&width=300",
        available: true,
      },
      {
        id: "pet2",
        name: "Luna",
        species: "Cat",
        breed: "Siamese",
        age: 2,
        gender: "Female",
        image: "/placeholder.svg?height=200&width=300",
        available: false,
      },
    ],
  },
  {
    id: "user2",
    name: "Samantha Lee",
    username: "samlee",
    avatar: "/placeholder.svg",
    coverImage: "/placeholder.svg?height=300&width=800",
    bio: "Cat mom and veterinary student. Passionate about animal welfare.",
    location: "Boston, MA",
    posts: 87,
    followers: 2340,
    following: 512,
    pets: [
      {
        id: "pet3",
        name: "Oliver",
        species: "Cat",
        breed: "Maine Coon",
        age: 4,
        gender: "Male",
        image: "/placeholder.svg?height=200&width=300",
        available: true,
      },
      {
        id: "pet4",
        name: "Bella",
        species: "Cat",
        breed: "Ragdoll",
        age: 1,
        gender: "Female",
        image: "/placeholder.svg?height=200&width=300",
        available: true,
      },
    ],
  },
]

// Mock data for posts
export const posts = [
  {
    id: "post1",
    user: {
      id: "user1",
      name: "Alex Johnson",
      avatar: "/placeholder.svg",
    },
    content: "Max had the best time at the dog park today! Made so many new friends. #DogsOfPawConnect",
    image: "/placeholder.svg?height=400&width=600",
    likes: 42,
    comments: 7,
    timeAgo: "2 hours ago",
    isFollowing: true,
  },
  {
    id: "post2",
    user: {
      id: "user2",
      name: "Samantha Lee",
      avatar: "/placeholder.svg",
    },
    content: "Oliver is enjoying his new cat tree! Best purchase ever. #CatsOfPawConnect",
    image: "/placeholder.svg?height=400&width=600",
    likes: 78,
    comments: 12,
    timeAgo: "5 hours ago",
    isFollowing: true,
  },
  {
    id: "post3",
    user: {
      id: "user3",
      name: "Mike Wilson",
      avatar: "/placeholder.svg",
    },
    content: "Anyone have recommendations for a good vet in the Chicago area? My rabbit needs a checkup.",
    image: null,
    likes: 15,
    comments: 23,
    timeAgo: "1 day ago",
    isFollowing: false,
  },
  {
    id: "post4",
    user: {
      id: "user1",
      name: "Alex Johnson",
      avatar: "/placeholder.svg",
    },
    content: "Luna is not impressed with her new toy. Back to the drawing board!",
    image: "/placeholder.svg?height=400&width=600",
    likes: 36,
    comments: 4,
    timeAgo: "2 days ago",
    isFollowing: true,
  },
]

// Mock data for mating pets
export const matingPets = [
  {
    id: "mate1",
    name: "Rocky",
    species: "Dog",
    breed: "German Shepherd",
    age: 3,
    gender: "Male",
    image: "/placeholder.svg?height=200&width=300",
    description:
      "Energetic and friendly German Shepherd looking for a mate. AKC registered with excellent health records.",
    traits: ["Friendly", "Energetic", "Trained", "Healthy"],
    distance: 5,
  },
  {
    id: "mate2",
    name: "Daisy",
    species: "Dog",
    breed: "Labrador Retriever",
    age: 2,
    gender: "Female",
    image: "/placeholder.svg?height=200&width=300",
    description:
      "Sweet and gentle Labrador with a great temperament. Looking for a compatible mate with similar traits.",
    traits: ["Gentle", "Playful", "Healthy", "Good with kids"],
    distance: 12,
  },
  {
    id: "mate3",
    name: "Whiskers",
    species: "Cat",
    breed: "Persian",
    age: 3,
    gender: "Male",
    image: "/placeholder.svg?height=200&width=300",
    description: "Award-winning Persian cat with beautiful coat. Looking for a female Persian or similar breed.",
    traits: ["Calm", "Pedigree", "Show quality", "Healthy"],
    distance: 8,
  },
  {
    id: "mate4",
    name: "Bella",
    species: "Dog",
    breed: "Poodle",
    age: 4,
    gender: "Female",
    image: "/placeholder.svg?height=200&width=300",
    description: "Intelligent and elegant standard Poodle. Health tested and ready for mating.",
    traits: ["Intelligent", "Elegant", "Health tested", "Trained"],
    distance: 15,
  },
  {
    id: "mate5",
    name: "Leo",
    species: "Cat",
    breed: "Maine Coon",
    age: 3,
    gender: "Male",
    image: "/placeholder.svg?height=200&width=300",
    description: "Large and friendly Maine Coon with excellent lineage. Looking for a compatible female.",
    traits: ["Friendly", "Large", "Pedigree", "Healthy"],
    distance: 20,
  },
  {
    id: "mate6",
    name: "Coco",
    species: "Dog",
    breed: "French Bulldog",
    age: 2,
    gender: "Female",
    image: "/placeholder.svg?height=200&width=300",
    description: "Healthy French Bulldog with excellent temperament. Looking for a compatible mate.",
    traits: ["Playful", "Healthy", "Good temperament", "Pedigree"],
    distance: 7,
  },
]

// Mock data for walk buddies
export const walkBuddies = [
  {
    id: "buddy1",
    name: "Chris Parker",
    avatar: "/placeholder.svg",
    location: "Downtown, San Francisco",
    distance: 2,
    bio: "Morning walker with my Golden Retriever. Looking for regular walking buddies in the downtown area.",
    petType: "dog",
    pets: [
      {
        name: "Buddy",
        image: "/placeholder.svg?height=100&width=100",
      },
    ],
    preferences: ["Morning walks", "Weekdays", "Dog-friendly parks"],
  },
  {
    id: "buddy2",
    name: "Emma Wilson",
    avatar: "/placeholder.svg",
    location: "Marina District, San Francisco",
    distance: 5,
    bio: "Evening dog walker with two friendly Labradors. Love meeting new dogs and their humans!",
    petType: "dog",
    pets: [
      {
        name: "Charlie",
        image: "/placeholder.svg?height=100&width=100",
      },
      {
        name: "Lucy",
        image: "/placeholder.svg?height=100&width=100",
      },
    ],
    preferences: ["Evening walks", "Weekends", "Beach walks"],
  },
  {
    id: "buddy3",
    name: "David Kim",
    avatar: "/placeholder.svg",
    location: "Mission District, San Francisco",
    distance: 3,
    bio: "Cat owner who takes my Bengal for leashed walks in quiet areas. Looking for other adventure cat owners.",
    petType: "cat",
    pets: [
      {
        name: "Simba",
        image: "/placeholder.svg?height=100&width=100",
      },
    ],
    preferences: ["Quiet areas", "Afternoons", "Short walks"],
  },
  {
    id: "buddy4",
    name: "Sarah Johnson",
    avatar: "/placeholder.svg",
    location: "Pacific Heights, San Francisco",
    distance: 7,
    bio: "Dog trainer with a well-behaved Border Collie. Happy to help with training tips during walks!",
    petType: "dog",
    pets: [
      {
        name: "Rex",
        image: "/placeholder.svg?height=100&width=100",
      },
    ],
    preferences: ["Any time", "Training focused", "Active walks"],
  },
]

// Mock data for walk events
export const walkEvents = [
  {
    id: "event1",
    title: "Golden Retriever Meetup",
    date: "Mar 30, 2025",
    time: "10:00 AM",
    location: "Golden Gate Park, SF",
    image: "/placeholder.svg?height=200&width=400",
    description: "Monthly meetup for Golden Retrievers and their owners. Come join us for fun and games!",
    attendees: [
      { name: "Alex", avatar: "/placeholder.svg" },
      { name: "Emma", avatar: "/placeholder.svg" },
      { name: "John", avatar: "/placeholder.svg" },
      { name: "Sarah", avatar: "/placeholder.svg" },
      { name: "Mike", avatar: "/placeholder.svg" },
      { name: "Lisa", avatar: "/placeholder.svg" },
      { name: "Tom", avatar: "/placeholder.svg" },
    ],
  },
  {
    id: "event2",
    title: "Small Dogs Playdate",
    date: "Apr 5, 2025",
    time: "3:00 PM",
    location: "Dolores Park, SF",
    image: "/placeholder.svg?height=200&width=400",
    description: "A special playdate for small dogs under 20 pounds. Safe environment with separate area.",
    attendees: [
      { name: "Jessica", avatar: "/placeholder.svg" },
      { name: "David", avatar: "/placeholder.svg" },
      { name: "Amy", avatar: "/placeholder.svg" },
      { name: "Robert", avatar: "/placeholder.svg" },
    ],
  },
  {
    id: "event3",
    title: "Beach Walk & Cleanup",
    date: "Apr 12, 2025",
    time: "9:00 AM",
    location: "Ocean Beach, SF",
    image: "/placeholder.svg?height=200&width=400",
    description: "Combine a fun beach walk with your dog and help clean up the environment. Bags provided!",
    attendees: [
      { name: "Chris", avatar: "/placeholder.svg" },
      { name: "Olivia", avatar: "/placeholder.svg" },
      { name: "James", avatar: "/placeholder.svg" },
      { name: "Sophia", avatar: "/placeholder.svg" },
      { name: "Daniel", avatar: "/placeholder.svg" },
      { name: "Emily", avatar: "/placeholder.svg" },
    ],
  },
  {
    id: "event4",
    title: "Adventure Cats Exploration",
    date: "Apr 18, 2025",
    time: "4:00 PM",
    location: "Sutro Heights Park, SF",
    image: "/placeholder.svg?height=200&width=400",
    description: "For trained cats on leashes who enjoy outdoor adventures. Quiet environment, slow pace.",
    attendees: [
      { name: "David", avatar: "/placeholder.svg" },
      { name: "Mia", avatar: "/placeholder.svg" },
      { name: "Noah", avatar: "/placeholder.svg" },
    ],
  },
]

// Mock data for conversations
export const conversations = [
  {
    id: "conv1",
    user: {
      id: "user2",
      name: "Samantha Lee",
      avatar: "/placeholder.svg",
      isOnline: true,
    },
    lastMessage: "Would you be interested in arranging a playdate for our cats?",
    lastMessageTime: "10 min ago",
    unreadCount: 2,
    startDate: "March 15, 2025",
    messages: [
      {
        id: "msg1",
        content: "Hi Alex! I saw your profile and noticed you have a Siamese cat too.",
        sender: "them",
        timestamp: "Mar 15, 10:30 AM",
      },
      {
        id: "msg2",
        content: "Hey Samantha! Yes, Luna is a Siamese. Your Oliver is gorgeous!",
        sender: "me",
        timestamp: "Mar 15, 10:35 AM",
      },
      {
        id: "msg3",
        content: "Thanks! Oliver is very social with other cats. How old is Luna?",
        sender: "them",
        timestamp: "Mar 15, 10:38 AM",
      },
      {
        id: "msg4",
        content: "Luna is 2 years old. She's a bit shy at first but warms up quickly.",
        sender: "me",
        timestamp: "Mar 15, 10:40 AM",
      },
      {
        id: "msg5",
        content: "Would you be interested in arranging a playdate for our cats?",
        sender: "them",
        timestamp: "10 min ago",
      },
    ],
  },
  {
    id: "conv2",
    user: {
      id: "user3",
      name: "Mike Wilson",
      avatar: "/placeholder.svg",
      isOnline: false,
    },
    lastMessage: "I found a great vet in your area. I'll send you the details.",
    lastMessageTime: "2 hours ago",
    unreadCount: 0,
    startDate: "March 10, 2025",
    messages: [
      {
        id: "msg1",
        content: "Hey, do you know any good vets in San Francisco?",
        sender: "me",
        timestamp: "Mar 10, 3:15 PM",
      },
      {
        id: "msg2",
        content: "I'm actually looking for one too for my rabbit!",
        sender: "them",
        timestamp: "Mar 10, 3:20 PM",
      },
      {
        id: "msg3",
        content: "Let me know if you find a good one. Max needs his annual checkup.",
        sender: "me",
        timestamp: "Mar 10, 3:22 PM",
      },
      {
        id: "msg4",
        content: "I found a great vet in your area. I'll send you the details.",
        sender: "them",
        timestamp: "2 hours ago",
      },
    ],
  },
  {
    id: "conv3",
    user: {
      id: "user4",
      name: "Emma Davis",
      avatar: "/placeholder.svg",
      isOnline: true,
    },
    lastMessage: "Max and Rex got along so well at the park yesterday!",
    lastMessageTime: "Yesterday",
    unreadCount: 1,
    startDate: "March 5, 2025",
    messages: [
      {
        id: "msg1",
        content: "Hi Alex! I'm Emma, I saw you at the dog park yesterday with your Golden Retriever.",
        sender: "them",
        timestamp: "Mar 5, 5:30 PM",
      },
      {
        id: "msg2",
        content: "Hi Emma! Yes, that was me and Max. Did you have the Border Collie?",
        sender: "me",
        timestamp: "Mar 5, 5:35 PM",
      },
      {
        id: "msg3",
        content: "Yes, that's Rex! He's 2 years old and full of energy.",
        sender: "them",
        timestamp: "Mar 5, 5:38 PM",
      },
      {
        id: "msg4",
        content: "Max is 3 and also very energetic. They seemed to play well together!",
        sender: "me",
        timestamp: "Mar 5, 5:40 PM",
      },
      {
        id: "msg5",
        content: "Max and Rex got along so well at the park yesterday!",
        sender: "them",
        timestamp: "Yesterday",
      },
    ],
  },
  {
    id: "conv4",
    user: {
      id: "user5",
      name: "David Chen",
      avatar: "/placeholder.svg",
      isOnline: false,
    },
    lastMessage: "Thanks for the mating info. I'll think about it and get back to you.",
    lastMessageTime: "2 days ago",
    unreadCount: 0,
    startDate: "February 28, 2025",
    messages: [
      {
        id: "msg1",
        content: "Hello, I'm interested in your Golden Retriever for mating with my female.",
        sender: "them",
        timestamp: "Feb 28, 10:15 AM",
      },
      {
        id: "msg2",
        content: "Hi David! Max is AKC registered and has all his health clearances. Can you tell me about your dog?",
        sender: "me",
        timestamp: "Feb 28, 10:30 AM",
      },
      {
        id: "msg3",
        content: "She's a 3-year-old Golden named Bella, also AKC registered with OFA hip and elbow clearances.",
        sender: "them",
        timestamp: "Feb 28, 10:45 AM",
      },
      {
        id: "msg4",
        content: "Sounds promising! I'd be happy to discuss further. Max has a great temperament and is very healthy.",
        sender: "me",
        timestamp: "Feb 28, 11:00 AM",
      },
      {
        id: "msg5",
        content: "Thanks for the mating info. I'll think about it and get back to you.",
        sender: "them",
        timestamp: "2 days ago",
      },
    ],
  },
]

// Mock data for notifications
export const notifications = [
  {
    id: "notif1",
    name: "Samantha Lee",
    avatar: "/placeholder.svg",
    content: "liked your post about Max at the dog park.",
    time: "5 minutes ago",
    read: false,
  },
  {
    id: "notif2",
    name: "Mike Wilson",
    avatar: "/placeholder.svg",
    content: 'commented on your photo: "Luna looks so cute!"',
    time: "15 minutes ago",
    read: false,
  },
  {
    id: "notif3",
    name: "Emma Davis",
    avatar: "/placeholder.svg",
    content: "sent you a message.",
    time: "1 hour ago",
    read: false,
  },
  {
    id: "notif4",
    name: "PawConnect",
    avatar: "/placeholder.svg",
    content: 'A new walk event was created near you: "Golden Retriever Meetup"',
    time: "2 hours ago",
    read: true,
  },
  {
    id: "notif5",
    name: "David Chen",
    avatar: "/placeholder.svg",
    content: "is interested in mating with your pet Max.",
    time: "Yesterday",
    read: true,
  },
  {
    id: "notif6",
    name: "Sarah Johnson",
    avatar: "/placeholder.svg",
    content: "wants to connect as a walk buddy.",
    time: "2 days ago",
    read: true,
  },
  {
    id: "notif7",
    name: "PawConnect",
    avatar: "/placeholder.svg",
    content: "Your pet profile for Max has been viewed 15 times this week!",
    time: "3 days ago",
    read: true,
  },
  {
    id: "notif8",
    name: "Chris Parker",
    avatar: "/placeholder.svg",
    content: "started following you.",
    time: "4 days ago",
    read: true,
  },
  {
    id: "notif9",
    name: "PawConnect",
    avatar: "/placeholder.svg",
    content: "Welcome to PawConnect! Complete your profile to get started.",
    time: "1 week ago",
    read: true,
  },
]

